### PR TITLE
Our Team 

### PR DESCRIPTION
**Pull request by charlisable**
finished our team page including accessibility fixes and added the updated footer.

### CODE REVIEW

**Review by MaidenManitoba — COMMENTED** [review]
Screenshot 2024-01-30 114642

The modal button needs minor adjustment. The modals don't open for the cards. 
Looks great besides the minor changes!

**Review by samifa308 — COMMENTED** [review]
just a few fixes with the modals, but other then that it looks good

**Comment by charlisable** [comment]
fixed issue with the footer modal close button by targeting only team modal styles

**Comment by roguemacaroon** [comment]
This is looking great, ran successful WAVE and lighthouse scans for accessibility,
Noticed the contact us buttons (current positions and get involved) do not link to the contact page, maybe that could be added (lines 151 and 178 in team.html)

**Comment by liannarice** [comment]
fixed button issues

**Review by maxharrisnet — APPROVED** [review]
Great job!

**Pull request merged**
